name: torch
channels:
  - powerai
  - plotly
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python 3.8.*
  - pytorch
  - torchvision
  - cpuonly
  - scipy
  - numpy
  - opencv
  - pandas
  - matplotlib
  - dash
  - dash-bootstrap-components
  - flask-caching
  - chart-studio
  - yaml
  - gym


