name: torch37
channels:
  - powerai
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python 3.7.*
  - pytorch
  - torchvision
  - cpuonly
  - scipy
  - numpy
  - opencv
  - pandas
  - matplotlib
  - dash
  - dash-bootstrap-components
  - flask-caching
  - yaml
  - gym
  - jupyter
  - cython


